### ISSUE TITLE
Link to expo or snack for demos?

### ISSUE THREAD

**Issue by nainardev** [mobily/stacks#1]

**Comment by mobily** [comment]
@nainardev it's not ready yet. As for now, you can clone the repo and after installing all dependencies run the example using `yarn dev` and `yarn start:ios` commands. After that, you can uncomment particular examples here: https://github.com/mobily/stacks/blob/3515920efca5ebc436b1824c1156df6978f0097b/example/src/screens/Root/index.tsx#L31

However, this is definitely on my TODO list.

**Comment by mobily** [comment]
@nainardev `snacks` with examples have been added to the docs, and as for now, I'm closing this issue ;)

**Comment by nainardev** [comment]
ThankS!!
