### ISSUE TITLE
Horizontal stack component (HStack?)

### ISSUE THREAD

**Issue by gfpacheco** [mobily/stacks#12]
Hi again, have you considered the possibility of having a horizontal version of the Stack?

We can do that with Columns+Column, but we have to create a Column component for each child.

We can almost do that with Inline, but I miss the vertical alignment prop.

It would be something as easy to use as the Stack, but horizontal.

**Comment by mobily** [comment]
@gfpacheco thanks for the suggestion and sorry for the late reply, this new feature will be added to the `Stack` component in `v1.0.x` :) stay tuned!

**Comment by mobily** [comment]
@gfpacheco the `horizontal` prop has been added to `Stack` in `v1.1.0`, see more: https://mobily.github.io/stacks/docs/components/stack
https://mobily.github.io/stacks/docs/changelog
