### ISSUE TITLE
Why not allow padding/margin props on Stacks?

### ISSUE THREAD

**Issue by tomparkp** [mobily/stacks#14]
I suspect there is a reason for this but I'm curious - why not allow margin/padding props to be passed to stacks and other components?

Often you're required to add additional clutter to the tree:

```
<Box paddingY={4}>
  <Stack space={2}>
     ...
  </Stack>
</Box>
```

vs

```
<Stack space={2} paddingY={4}>
 ...
</Stack>
```

**Comment by mobily** [comment]
@tomparkp added in `v1.1.0` :)
