### ISSUE TITLE
Inline and Stack + horizontal won't let their children grow

### ISSUE THREAD

**Issue by jsamr** [mobily/stacks#16]
### Description

Children of `Stack` (+ `horizontal` prop) and `Inline` components with a `flexGrow: 1` style won't grow horizontally. 

### Minimal, Reproducible Example

```jsx
import * as React from 'react';
import {Text, View} from 'react-native';
import {Stack, Inline, StacksProvider} from '@mobily/stacks';

function HorizontalStackSample() {
  return (
    <Stack space={0} horizontal style={{flexGrow: 0, backgroundColor: 'gray'}}>
      <View style={{width: 40, height: 100, backgroundColor: 'red'}} />
      <View style={{flexGrow: 1, height: 100, backgroundColor: 'purple'}} />
    </Stack>
  );
}

function InlineSample() {
  return (
    <Inline space={0} style={{flexGrow: 0, backgroundColor: 'gray'}}>
      <View style={{width: 40, height: 100, backgroundColor: 'red'}} />
      <View style={{flexGrow: 1, height: 100, backgroundColor: 'purple'}} />
    </Inline>
  );
}

function HorizontalViewSample() {
  return (
    <View style={{flexGrow: 0, backgroundColor: 'black', flexDirection: 'row'}}>
      <View style={{width: 40, height: 100, backgroundColor: 'red'}} />
      <View style={{flexGrow: 1, height: 100, backgroundColor: 'purple'}} />
    </View>
  );
}

export default function App() {
  return (
    <StacksProvider spacing={5}>
      <Text>
        Horizontal Stack, expected to display a red box of width 40, and a
        purple box spanning the remaining horizontal space.
      </Text>
      <HorizontalStackSample />
      <Text>
        Inline, expected to display a red box of width 40, and a purple box
        spanning the remaining horizontal space.
      </Text>
      <InlineSample />
      <Text>
        Horizontal View, expected to display a red box of width 40, and a purple
        box spanning the remaining horizontal space.
      </Text>
      <HorizontalViewSample />
    </StacksProvider>
  );
}
```

![image](https://user-images.githubusercontent.com/3646758/113878906-67f31200-9790-11eb-908d-12b1865f550e.png)

### Test conditions

- @mobily/stacks@1.1.1
- react-native@0.63.3
- Platform: Android (Emulator)
- OS: Android 10

**PS**: Your project is awesome!

**Comment by mobily** [comment]
> Children of Stack (+ horizontal prop) and Inline components with a flexGrow: 1 style won't grow horizontally.

@jsamr 👋 , `flexGrow` will not work in this case, since all inner elements are wrapped into View components (see: [Stack](https://github.com/mobily/stacks/blob/74c0f603523f4bb04a203db3b40383348a7bbb5a/src/Stacks_component_Stack.res#L170) and [Inline](https://github.com/mobily/stacks/blob/74c0f603523f4bb04a203db3b40383348a7bbb5a/src/Stacks_component_Inline.res#L162)) and you can't control them, you may want to use either a combination of `Columns` and `Column`:
https://codesandbox.io/s/issue-16-1-lej4n?file=/src/App.js

or simply with `Box` (if you don't need spacing between inner elements):
https://codesandbox.io/s/issue-16-2-fid63?file=/src/App.js (however, it looks the same as `HorizontalViewSample`)

> PS: Your project is awesome!

thank you, I really appreciate that! ❤️

**Comment by jsamr** [comment]
@mobily An other approach would be to use `cloneElement` and just add the generated styles to the style prop... what do you think?

**Comment by jsamr** [comment]
Something like this:
```js
// Does it acts like React.Children.map?
Belt.Array.mapWithIndexU(children, (index, child) => {
  // test child is an element first
  if (typeof child === "string") {
    throw new Error("...");
  }
  return React.cloneElement(
    child,
    {
      ...child.props,
      style: [
        child.style,
        Style.arrayOption([
          width,
          resolveAlignItemsX(align),
          debugStyle,
          isLast(index) ? None : Some(marginFn(space)),
        ]),
      ],
    }
  );
});
```

**Comment by mobily** [comment]
@jsamr the initial implementation of `Stacks` components was based on `cloneElement` but unfortunately, it had performance issues (for instance in conjunction with React Native SVG elements) and I'd rather avoid using `cloneElement` (also, in ReScript `cloneElement` is useful only for interoping with JS modules, and it isn't recommended to use in ReScript components body)

anyway, the `horizontal` prop is still sort of "experimental", and I believe, there is room for improvements :)

**Comment by jsamr** [comment]
@mobily OK, thanks for this clarification :-) I guess it's a pitfal worth mentioning in the docs! Keep up with the good work :rocket:
