### ISSUE TITLE
Expo Snack cannot import 1.1.5 or 1.1.6

### ISSUE THREAD

**Issue by rborn** [mobily/stacks#23]
Just try to create a snack.expo.io with any of 1.1.5/6 and it will fail

<img width="367" alt="Screenshot 2021-05-12 at 14 35 22" src="https://user-images.githubusercontent.com/406409/117975770-540e7300-b32f-11eb-91af-62774c37c6ba.png">
<img width="760" alt="Screenshot 2021-05-12 at 14 35 17" src="https://user-images.githubusercontent.com/406409/117975772-54a70980-b32f-11eb-8944-770c76efdb5e.png">

**Comment by mobily** [comment]
thanks for reporting! `Stacks` needs additional configuration in Expo (web), also, be aware that Expo Snack bundles the code differently than Expo CLI and React Native CLI

you can read more here: https://mobily.github.io/stacks/docs/react-native-web#expo and here https://docs.expo.io/workflow/snack/#adding-a-library

**Comment by rborn** [comment]
Understood, however with 1.1.4 was working 🧐

**Comment by mobily** [comment]
I will look into it once again (I feel there's room for improvements in terms of the web config), but for now, it doesn't have a high priority to me :)

**Comment by mobily** [comment]
@rborn fixed in `v1.1.8` 😉 (if `"@mobily/stacks": "1.1.8` doesn't work, use `"@mobily/stacks": "1.1.8-rc.0"` instead, I don't know how the cache system works there ¯\\_(ツ)_/¯)

**Comment by rborn** [comment]
Tested with 1.2.0, works great, thank you 🥰
