### ISSUE TITLE
Column (and Stack) won't expand to it's content in 1.1.5/6

### ISSUE THREAD

**Issue by rborn** [mobily/stacks#24]
Without any code change from 1.1.4 to 1.1.5/6 it seems that Columns and Stack lost the ability to expand to its content in React-Native-Web.

<img width="535" alt="Screenshot 2021-05-12 at 15 42 50" src="https://user-images.githubusercontent.com/406409/117985365-eb2bf880-b338-11eb-802b-bea07a3f79e4.png">

This however works: ` <Column style={{ flex: 1 }}>`

<img width="555" alt="Screenshot 2021-05-12 at 15 43 01" src="https://user-images.githubusercontent.com/406409/117985361-e9facb80-b338-11eb-89a7-87c3d7c6382b.png">

Code: 
~~~
               <Column width={'content'} style={{ backgroundColor: 'pink', flex: 1 }}>
                     <Box alignX={'center'} alignSelf={'right'} flex={'fluid'}>
                        <Box
                            alignX={'center'}
                            alignY={'center'}
                            style={index <= currentPosition ? checkStyles.wrapperActive : checkStyles.wrapperInactive}
                        >
                            {index <= currentPosition && (
                                <Box alignX={'center'} alignY={'center'} style={checkStyles.currentContent}>
                                    <EmText color={colors.white}>
                                        {index < currentPosition || currentPosition === 2 ? (
                                            <Image
                                                source={images.webapp.onboardingCheck}
                                                style={checkStyles.checkImage}
                                            />
                                        ) : (
                                            index + 1
                                        )}
                                    </EmText>
                                </Box>
                            )}

                            {index > currentPosition && (
                                <EmText style={{ color: colors.neutral.c100 }}>{index + 1}</EmText>
                            )}
                        </Box>

                        {index < lastStep && (
                            <Box flex={'fluid'}>
                                {index <= currentPosition && <Box flex={'fluid'} style={checkStyles.ligatureActive} />}

                                {index >= currentPosition && (
                                    <Box flex={'fluid'} style={checkStyles.ligatureInactive} />
                                )}
                            </Box>
                        )}
                    </Box>
                </Column>
                
~~~

**Comment by mobily** [comment]
@rborn I'm looking at those screenshots, and I'm not sure what's the issue here? 😅 there weren't any changes in `Columns/Stack` in the last two versions `v1.1.5/6`, are you sure the problem isn't on your end? could you provide a basic example with this issue? :)

**Comment by rborn** [comment]
Hi,

So the first screenshot is how Column behaves with 1.1.5/6 without adding ` flex:1` and the second one is the correct behaviour. 

Before it was working without the need to add flex in style ( not sure it was 1.1.4 or 0.9.6 though 😅

I will try to create a simpler example

**Comment by rborn** [comment]
@mobily ok, added the example : https://github.com/rborn/stacks_box_style_issues/blob/master/src/App.js#L32

set in package.json 0.9.4 - ✅ 


<img width="818" alt="Screenshot 2021-05-12 at 17 05 22" src="https://user-images.githubusercontent.com/406409/117998732-75c62500-b344-11eb-92e3-00c7ffc60a47.png">

set in package.json 1.1.6 - 💥 

<img width="776" alt="Screenshot 2021-05-12 at 17 04 04" src="https://user-images.githubusercontent.com/406409/117998755-7c549c80-b344-11eb-8d0e-c731f813a118.png">


change to `<Column width={"content"} style={{ flex: 1 }}>` and works again (with 1.1.6)

Thanks a lot 😻

**Comment by rborn** [comment]
@mobily thanks a lot, seems to work ( at least in the example) will report back in case I found anything 🥰
