### ISSUE TITLE
A lot of undefined styles in styles array

### ISSUE THREAD

**Issue by erikmueller** [mobily/stacks#25]
I noticed a lot of `undefined`s in the style array of the rendered components (e.g. `FillView`). I have converted a layout to stacks (which makes things much much easier btw 👌 ) and was confused when a snapshot showed a lot of new additions.
I then checked the actual rednered output with the RN Debugger and found that `Box` rendered by the `FillView` component look like this:

![image](https://user-images.githubusercontent.com/2292532/118936914-45d2df00-b94d-11eb-870f-1f09cd38dc8c.png)

It already has a couple of `undefined`s. When I checked the View that is rendered by the `Box` I found even more:

![image](https://user-images.githubusercontent.com/2292532/118937152-7ca8f500-b94d-11eb-9bff-0223c8d5a847.png)

The source just look like this: `<FillView alignY="center">...</FillView>`.
This is also the case for other components such as `Stack`.

So I guess my question is: Am I doing something wrong, is this something that does not matter or is something wrong with the way styles are attached/read?

Also: Great work, love the project. Makes things so much more consistent and is a breeze to work with ❤️

**Comment by mobily** [comment]
@erikmueller 👋 thanks for reporting this problem! I assume it should not affect the performance in the end, but I have removed `undefined` values in the styles array, just in case! 😉 shipped in `v1.1.8` 🚢
