### ISSUE TITLE
What's the bundle size?

### ISSUE THREAD

**Issue by kg-currenxie** [mobily/stacks#26]
No sure why it can't be built on bundlephobia :)
https://bundlephobia.com/result?p=@mobily/stacks

I'm thinking of using this on the web (react-native-web). That's why I wanna know :)
Potentially fixing the bundlephobia issue could help others finding out :)

**Comment by mobily** [comment]
> No sure why it can't be built on bundlephobia :)

me neither, and I have no idea why it fails, anyway here are the numbers you're looking for:

![image](https://user-images.githubusercontent.com/1467712/119242039-04b01a00-bb5b-11eb-95d4-c6ea71bac72d.png)

**Comment by kg-currenxie** [comment]
Thank you! :)
