### ISSUE TITLE
Update from 1.3.1 fails to render

### ISSUE THREAD

**Issue by rborn** [mobily/stacks#34]
Hi, 

I have a weird issue where if I update to any version from 1.3.1 ( even 1.4.0)  the app will simply stay on the splash screen. 
It won't render anything and it behaves like it doesn't even load any other file.

Any idea what it might be ?

Thank you.

(I can't really provide a test case because I can't reproduce this outside my repo :(  )

**Comment by mobily** [comment]
hey @rborn, sorry for the late response! do you still have a problem? I'm not sure if it's a problem with Stacks itself, since I have been using Stacks in a few projects lately and I had no issues like yours

**Comment by rborn** [comment]
I will try again and let you know, thank you

**Comment by rborn** [comment]
Sorry for the late reply, I'll ping you with updates as soon as I try again. Sorry again ❤️
