### ISSUE TITLE
maxHeight issue in Rows

### ISSUE THREAD

**Issue by LTAbhirup** [mobily/stacks#36]
I have a component which use Rows and it has two child Row. Inside the second child row i have three box elements with flex value as "content", "fluid", "content" respectively.Basically it is to render a fixed header and footer, and the middle one will be flexible (depending on the content). Now, i am setting style={{maxHeight: 0.7*WINDOW_HEIGHT}} in the parent Rows.
The issue is even if that middle content is having _lesser_ _content_, the height is still remaining at 70% of window height.
 Ideally it should be flexible depending on the content.

**Comment by mobily** [comment]
@LTAbhirup could you provide the JSX markup?

**Comment by LTAbhirup** [comment]
@mobily  jsx
`
<Rows style={{ maxHeight: 0.7 * WINDOW_HEIGHT}}>
       <Row>//Another row </Row>
       <Row
          style={{backgroundColor: '#fff'}}
          height="fluid"
          paddingX={4}
          paddingY={6}
        >
          {HeaderComponent && <Header>{HeaderComponent}</Header>} // Header is a box with flex="content"
          <Box flex="fluid">{children}</Box>       
          {FooterComponent && <Footer>{FooterComponent}</Footer>} // Header is a box with flex="content"
        </Row>
      </Rows>
</Rows>
`

**Comment by LTAbhirup** [comment]
@mobily any update on this ?

**Comment by LTAbhirup** [comment]
![45466795-c258-4dda-9005-f3ad2f4736fc](https://user-images.githubusercontent.com/104512954/167756974-f3031594-497e-4fda-84a7-add65c1dbba6.png)

@mobily as per the screenshot of your app, i would like that "C" box to take only only the text height .Currently it is taking the remaining height. If the text increases, so the height will also increase.

In my screenshot , I am trying to make a bottommodal which uses the react-native-modal library .The children may be either text / flatlist / scolllview(should be scrollable only when maxHeight is reached.

**Comment by mobily** [comment]
@LTAbhirup hey again! I have a strong feeling that in this specific case you should use a different approach and different components, here's a solution with no `Rows/Row`:

```tsx
<Modal
  isVisible={visible}
  useNativeDriver={true}
  useNativeDriverForBackdrop={true}
  avoidKeyboard={true}
  onBackdropPress={handleClose}
  onBackButtonPress={handleClose}
  style={styles.modal}
  backdropColor={palette.text}
  backdropOpacity={0.5}
  testID="BottomSheet_container"
>
  <Box flex="fluid" alignY="bottom">
    <Box alignX="center" marginBottom={4.5}>
      <IconButton
        name="arrow-bottom"
        color={palette.gray300}
        style={{ backgroundColor: palette.text }}
        onPress={handleClose}
      />
    </Box>
    {HeaderComponent ? <Header>{HeaderComponent}</Header> : null}
    <Box
      style={{
        ...styles.content,
        maxHeight: 0.5 * WINDOW_HEIGHT,
        backgroundColor: '#fff',
      }}
      paddingX={4}
      paddingY={6}
    >
      {children}
    </Box>
    {FooterComponent ? <Footer>{FooterComponent}</Footer> : null}
  </Box>
</Modal>
``` 

and the final result:

<img width="473" alt="CleanShot 2022-06-05 at 18 41 10@2x" src="https://user-images.githubusercontent.com/1467712/172061045-a0006154-5b4a-452e-a982-6cc3c1aca322.png">
<img width="473" alt="CleanShot 2022-06-05 at 18 41 10@2x" src="https://user-images.githubusercontent.com/1467712/172061071-78ae9dc6-813b-492a-97f0-68ecb55c96e3.gif">

I'm going to close this issue, if there are any other problems, please open a new issue

**Comment by LTAbhirup** [comment]
Thanks @mobily . I will check.
