### ISSUE TITLE
Rendering issue when switching screen using react-navigation in combination w/ react-native-web

### ISSUE THREAD

**Issue by nikgraf** [mobily/stacks#37]
When switching to the page it looks like this:
<img width="532" alt="Screenshot 2022-05-13 at 13 15 47" src="https://user-images.githubusercontent.com/223045/168272539-b5e55be9-df6c-45e7-981a-41696e499a4d.png">

When refreshing the page it looks like this (and this is how it supposed to be):
<img width="522" alt="Screenshot 2022-05-13 at 13 15 55" src="https://user-images.githubusercontent.com/223045/168272602-b1838c14-b417-4f3d-a5b1-82559b161265.png">

Code:
```jsx
      <Text style={tw`mt-4 mb-1`}>Nodes</Text>
      <Tiles style={tw`max-w-lg`} space={4} columns={10}>
        <Icon name="at-line" />
        <Icon name="code-s-slash-line" />
        <Icon name="double-quotes-l" />
        <Icon name="heading" />
        <Icon name="h-1" />
        <Icon name="h-2" />
        <Icon name="h-3" />
        <Icon name="h-4" />
        <Icon name="h-5" />
        <Icon name="h-6" />
        <Icon name="indent-decrease" />
        <Icon name="indent-increase" />
        <Icon name="list-check" />
        <Icon name="list-check-2" />
        <Icon name="list-ordered" />
        <Icon name="list-unordered" />
        <Icon name="paragraph" />
        <Icon name="table-2" />
        <Icon name="text" />
      </Tiles>
```

This seems like a general issue with the library. I also noticed it on other pages. Any ideas?

**Comment by nikgraf** [comment]
@mobily seems like it's an issue with react-native-web itself or react-navigation because I noticed it also happens on screens where `stacks` is not used

**Comment by nikgraf** [comment]
Actually realized we used stacks more than I thought and all cases were stacks related.

For a horizontal stack I nailed down the issue to a broken flex-ba
<img width="402" alt="Screenshot 2022-05-17 at 22 33 48" src="https://user-images.githubusercontent.com/223045/168905266-ca3cc912-7ca0-4996-9e94-77ee85e48e7f.png">
sis setting.

This might be related: https://github.com/necolas/react-native-web/issues/1264

**Comment by mobily** [comment]
hello @nikgraf! 👋 thanks for posting this issue, could you try with [v2.1.0](https://github.com/mobily/stacks/releases/tag/v2.1.0), please? also, if this still occurs, a repro repo would be helpful! 🙏

**Comment by nikgraf** [comment]
@mobily still happening :(

<img width="998" alt="Screenshot 2022-06-09 at 13 52 31" src="https://user-images.githubusercontent.com/223045/172840797-0c9d70e2-650c-4ea8-932e-efd7bc388108.png">

**Comment by nikgraf** [comment]
sorry, don't have time to setup a full repro. we are using react-navigation and after switching between screens it sometimes happens. Could be something wrong with our setup

**Comment by vbylen** [comment]
@nikgraf I replaced all instances of `<Stack/>` and `<Inline/>` with `<Box/>`, and removed flex='content'. This seems to have solved the problem. Not ideal, but it works.

**Comment by makhataibar** [comment]
I was update react-native-web to latest version (0.18.1) and all works correctly now. But I don't know, can I upgrade RNW without Expo migration guide?
