### ISSUE TITLE
Second to last child keeps bottom margin after last child is removed

### ISSUE THREAD

**Issue by gfpacheco** [mobily/stacks#6]
Repro: https://snack.expo.io/@gfpacheco/stacks-bug

**Comment by mobily** [comment]
@gfpacheco nice catch, thanks for reporting this issue! :)

**Comment by mobily** [comment]
@gfpacheco it's been fixed and published in `v0.8.2` :)

**Comment by gfpacheco** [comment]
That's great! Thanks for the quick response, I didn't even have time to try and fix it myself
